export const Colors = {
  light: {
    text: '#1C1C1C',
    textMuted: '#5F5F5F',
    background: 'transparent',
    backgroundTop: '#0D3B1E',
    backgroundMid: '#0A2C16',
    backgroundBottom: '#000000',
    surface: 'transparent',
    surfaceAlt: 'transparent',
    tint: '#E65C2E',
    buttonText: '#FFFFFF',
    accent: '#2E86AB',
    icon: '#5F5F5F',
    tabIconDefault: '#8A7C5A',
    tabIconSelected: '#E65C2E',
    divider: '#D6C9A5',
    success: '#3C9D23',
    danger: '#C0392B',
    tabBar: 'transparent',
    tabBarBorder: '#D0C39D',
    cardShadow: 'rgba(28, 28, 28, 0.12)',
  },
  dark: {
    text: '#F2E8C9',
    textMuted: '#C7BFA6',
    background: 'transparent',
    backgroundTop: '#0D3B1E',
    backgroundMid: '#0A2C16',
    backgroundBottom: '#000000',
    surface: 'transparent',
    surfaceAlt: 'transparent',
    tint: '#FF6B2E',
    buttonText: '#FFFFFF',
    accent: '#29A3D1',
    icon: '#C7BFA6',
    tabIconDefault: '#8A816A',
    tabIconSelected: '#FF6B2E',
    divider: '#2E3242',
    success: '#5AD24F',
    danger: '#FF4D4D',
    tabBar: 'transparent',
    tabBarBorder: '#232736',
    cardShadow: 'rgba(0, 0, 0, 0.6)',
  },
};

export const Fonts = {
  heading: 'SpaceGrotesk_700Bold',
  headingAlt: 'SpaceGrotesk_600SemiBold',
  body: 'SpaceGrotesk_400Regular',
  bodyMedium: 'SpaceGrotesk_500Medium',
  handwriting: 'Caveat_700Bold',
};


